"""add email & map_image in Location

Revision ID: 0efc717186bb
Revises: 463da75d1ea5
Create Date: 2026-05-14 17:35:26.440386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0efc717186bb'
down_revision: Union[str, Sequence[str], None] = '463da75d1ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('map_image_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('map_tg_file_id', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('map_tg_file_id')
        batch_op.drop_column('map_image_path')

    # ### end Alembic commands ###
